### ISSUE TITLE
Links to http://www.pighixxx.com are broken

### ISSUE THREAD

**Issue by aweinstein** [FPGAwars/apio-examples#14]
Hi:

The site http://www.pighixxx.com is not longer related to electronic boards.

There are a few examples that point to this site:

https://github.com/FPGAwars/apio-examples/blob/7dc3c222029e1a04797e3216ecb8878800d27f1f/icestick/leds/leds.pcf

https://github.com/FPGAwars/apio-examples/blob/7dc3c222029e1a04797e3216ecb8878800d27f1f/icestick/pcf/icestick.pcf

https://github.com/FPGAwars/apio-examples/blob/7dc3c222029e1a04797e3216ecb8878800d27f1f/icestick/template/icestick.pcf

**Comment by Obijuan** [comment]
Fixed! Thanks! :-)
